#summary Called when one of the callbacks threw an error

{{{
got_error(in_function_name:String, err:Error)
}}}

If any of your callbacks have raised an error, that error is caught and ClientGameAPI will call `got_error`.
In case of an error, you should call [do_client_protocol_error_with_description].
You should be very careful not to throw any exceptions in `got_error`, because these exceptions will be silently ignored.